name: Octo Organization CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Decompress
  uses: TonyBogdanov/zip@1.0
  with:
      args: unzip -qq ./lua-test.zip -d .
