name: Unzip lua-test and commit

on: [push]

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Decompress
  uses: TonyBogdanov/zip@1.0
  with:
      args: unzip -qq ./lua-test.zip -d ./target
